import type { Manufactory, Template } from './types'

export const seedManufactories: Manufactory[] = [
  {
    id: 'atelier-nordwear',
    name: 'Atelier Nordwear',
    contactPerson: 'Mara Stein',
    category: 'Streetwear',
    city: 'Hamburg',
    region: 'Hamburg',
    country: 'Deutschland',
    website: 'https://nordwear.example',
    email: 'studio@nordwear.example',
    phone: '+49 40 123456',
    social: '@ateliernordwear',
    products: 'Overshirts, Hoodies, Utility Pants',
    priceLevel: 'Premium',
    brandFit: 'A',
    cooperationPotential: 'Hoch',
    status: 'Antwort erhalten',
    priority: 'A',
    source: 'Instagram',
    lastContact: '2026-05-10',
    nextFollowUp: '2026-05-14',
    nextStep: 'Line Sheet anfragen',
    notes: 'Sehr guter Fashion-Fit: klare Streetwear-Silhouette, kleine Serien, DACH-Produktion prüfen.',
  },
  {
    id: 'maison-ligne',
    name: 'Maison Ligne',
    contactPerson: 'Claire Dubois',
    category: 'Ready-to-Wear',
    city: 'Paris',
    region: 'Ile-de-France',
    country: 'Frankreich',
    website: 'https://maisonligne.example',
    email: 'studio@maisonligne.example',
    phone: '+33 1 234567',
    social: '@maisonligne',
    products: 'Blazer, Wide-Leg Pants, Capsule Dresses',
    priceLevel: 'Premium',
    brandFit: 'A-',
    cooperationPotential: 'Hoch',
    status: 'Erstkontakt gesendet',
    priority: 'A-',
    source: 'Showroom Paris',
    lastContact: '2026-05-12',
    nextFollowUp: '2026-05-15',
    nextStep: 'Follow-up mit Lookbook senden',
    notes: 'Elegantes RTW-Label mit starker Capsule-Aesthetik, visuell passend fuer Agorase.',
  },
  {
    id: 'oro-atelier',
    name: 'Oro Atelier',
    contactPerson: 'Elena Rossi',
    category: 'Schmuck',
    city: 'Mailand',
    region: 'Lombardei',
    country: 'Italien',
    website: 'https://oro.example',
    email: 'contact@oro.example',
    phone: '',
    social: '@oroatelier',
    products: 'Statement-Ringe, Ketten, kleine Schmuckserien',
    priceLevel: 'Luxus',
    brandFit: 'B+',
    cooperationPotential: 'Mittel',
    status: 'Kontakt gefunden',
    priority: 'B',
    source: 'Pinterest',
    lastContact: '',
    nextFollowUp: '2026-05-18',
    nextStep: 'Wholesale-Kontakt vorbereiten',
    notes: 'Starke Accessoire-Sprache, Preisniveau und Marge prüfen.',
  },
  {
    id: 'grain-cut-studio',
    name: 'Grain Cut Studio',
    contactPerson: 'Jonas Weber',
    category: 'Schnitt & Prototyping',
    city: 'Wien',
    region: 'Wien',
    country: 'Oesterreich',
    website: 'https://graincut.example',
    email: '',
    phone: '+43 1 456789',
    social: '@graincutstudio',
    products: 'Schnittentwicklung, Prototyping, Kleinserienproduktion',
    priceLevel: 'Mittel',
    brandFit: 'A',
    cooperationPotential: 'Hoch',
    status: 'Kooperation in Prüfung',
    priority: 'A',
    source: 'Empfehlung',
    lastContact: '2026-05-09',
    nextFollowUp: '2026-05-20',
    nextStep: 'MOQ und Produktionsfenster klären',
    notes: 'Kann als Produktionspartner fuer Capsule Drops interessant sein.',
  },
  {
    id: 'denim-yard',
    name: 'Denim Yard',
    contactPerson: '',
    category: 'Denim',
    city: 'Leipzig',
    region: 'Sachsen',
    country: 'Deutschland',
    website: 'https://denimyard.example',
    email: '',
    phone: '',
    social: '@denimyard',
    products: 'Raw Denim, Workwear Pants, Washed Jackets',
    priceLevel: 'Mittel',
    brandFit: 'B',
    cooperationPotential: 'Mittel',
    status: 'Zu recherchieren',
    priority: 'B',
    source: 'Google',
    lastContact: '',
    nextFollowUp: '',
    nextStep: 'Wholesale-Kontakt recherchieren',
    notes: 'Interessanter Denim-Fokus, Kontakt und Produktionsland fehlen.',
  },
  {
    id: 'botanica-dye-lab',
    name: 'Botanica Dye Lab',
    contactPerson: 'Nora Klein',
    category: 'Sustainable Fashion',
    city: 'Zuerich',
    region: 'Zuerich',
    country: 'Schweiz',
    website: 'https://botanicadye.example',
    email: 'partners@botanicadye.example',
    phone: '+41 44 123456',
    social: '@botanicadye',
    products: 'Natural Dyeing, Organic Jersey, Garment Finishing',
    priceLevel: 'Premium',
    brandFit: 'A-',
    cooperationPotential: 'Hoch',
    status: 'Line Sheet / Samples angefragt',
    priority: 'A',
    source: 'Instagram',
    lastContact: '2026-05-11',
    nextFollowUp: '2026-05-16',
    nextStep: 'Material-Swatches nachhalten',
    notes: 'Sehr stimmige Sustainability-Story, Zertifikate und Skalierbarkeit prüfen.',
  },
]

export const seedTemplates: Template[] = [
  {
    id: 'erstkontakt',
    name: 'Erstkontakt',
    subject: 'Fashion-Kooperationsanfrage von Agorase',
    body: 'Hallo {{Ansprechpartner}},\n\nwir bauen bei Agorase eine kuratierte Fashion-Plattform fuer besondere Labels, Ateliers und Produktionspartner auf und sind auf {{Name}} aufmerksam geworden. Eure Arbeit passt aus unserer Sicht sehr gut zu unserer Richtung.\n\nHaettet ihr Interesse an einem kurzen Austausch zu Wholesale, Capsule Drops oder einer kuratierten Kooperation?',
  },
  {
    id: 'follow-up',
    name: 'Follow-up',
    subject: 'Kurzer Follow-up zu Agorase Fashion',
    body: 'Hallo {{Ansprechpartner}},\n\nich wollte freundlich nachfassen, ob unsere Anfrage zu Agorase bei euch angekommen ist. Wir wuerden uns sehr ueber eine kurze Rueckmeldung zu moeglichen Fashion-Kooperationen freuen.',
  },
  {
    id: 'katalog',
    name: 'Line-Sheet-/Sample-Anfrage',
    subject: 'Line Sheet, Wholesale-Konditionen oder Samples fuer Agorase',
    body: 'Hallo {{Ansprechpartner}},\n\nvielen Dank fuer eure Rueckmeldung. Koenntet ihr uns ein aktuelles Line Sheet, Wholesale-Konditionen, MOQ, Lieferfenster und Informationen zu Samples senden?',
  },
  {
    id: 'interesse',
    name: 'Antwort auf Interesse',
    subject: 'Naechste Schritte fuer eine Fashion-Kooperation',
    body: 'Hallo {{Ansprechpartner}},\n\nschoen, dass eine Kooperation fuer euch interessant klingt. Als naechsten Schritt wuerden wir gern Kollektion, Konditionen, Verfuegbarkeit und Timeline abstimmen.',
  },
  {
    id: 'spaeter',
    name: 'Später erneut kontaktieren',
    subject: 'Agorase Fashion Kontakt fuer spaeter vormerken',
    body: 'Hallo {{Ansprechpartner}},\n\nvielen Dank fuer eure Rueckmeldung. Wir merken uns {{Name}} gern fuer einen spaeteren Drop oder eine kommende Saison vor und melden uns wieder, wenn es besser passt.',
  },
]
